language: node_js
node_js: stable
cache:
  apt: true
  directories:
  - node_modules
before_install:
- export TZ='Asia/Taipei'
install:
- npm install
script:
- hexo clean
- hexo g
after_script:
- git clone https://${GH_REF} .deploy_git
- cd .deploy_git
- git checkout master
- cd ../
- mv .deploy_git/.git/ ./public/
- cd ./public
- git config user.name "FWcloud916"
- git config user.email "ree0916tw@gmail.com"
- git add .
- git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"
- git push --force --quiet "https://${HEXO_TOKEN}@${GH_REF}" master:master
branches:
  only:
  - develop
env:
  global:
  - GH_REF: github.com/FWcloud916/FWcloud916.github.io
notifications:
  email:
  - ree0916tw@gmail.com
  on_success: change
  on_failure: always